# Generated by Django 3.0.8 on 2020-07-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todostatus',
            fields=[
                ('todoid', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
